version: "3.8"

services:

  accounts:
    image: jackrichterdocker/eazybytes-accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network
   
  loans:
    image: jackrichterdocker/eazybytes-loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network
  
  cards:
    image: jackrichterdocker/eazybytes-cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eazybank-network  
   
networks:
  eazybank-network:

