apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_ZIPKIN_BASE-URL: http://zipkin-service:9411/
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eurekaserver-service:8070/eureka/
